# This patch add annotation to admission webhook config
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: metallb-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
