apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frr-k8s-daemon-scc
  namespace: metallb-system
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frr-k8s-daemon-scc-binding
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frr-k8s-daemon-scc
subjects:
  - kind: ServiceAccount
    name: frr-k8s-daemon
    namespace: metallb-system
