apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:
    feature.node.kubernetes.io/metalLB.capable: 'true'
  speakerTolerations:
  - key: "Example"
    operator: "Exists"
    effect: "NoExecute"
