# permissions for end users to view bfdprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bfdprofile-viewer-role
rules:
- apiGroups:
  - metallb.io.metallb.io
  resources:
  - bfdprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metallb.io.metallb.io
  resources:
  - bfdprofiles/status
  verbs:
  - get
