# permissions for end users to edit bfdprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bfdprofile-editor-role
rules:
- apiGroups:
  - metallb.io.metallb.io
  resources:
  - bfdprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metallb.io.metallb.io
  resources:
  - bfdprofiles/status
  verbs:
  - get
