apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: two-routers-vrf
  namespace: frr-k8s-system
spec:
  bgp:
    routers:
    - asn: 64513
      neighbors:
      - address: 172.32.0.3
        asn: 4200000000
        ebgpMultiHop: true
        port: 180
        toAdvertise:
          allowed:
            mode: all
      prefixes:
      - 192.168.2.0/24
      - 192.169.2.0/24
    - asn: 64515
      vrf: red
      neighbors:
      - address: 172.31.0.3
        asn: 4200000000
        port: 179
        toAdvertise:
          allowed:
            mode: all
      prefixes:
      - 192.168.2.0/24
      - 192.169.2.0/24
