apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-sample1
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 172.30.0.3
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-sample2
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 172.30.0.3
  bfdProfile: bfd-profile-sample
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-sample3
  namespace: metallb-system
spec:
  holdTime: 9m0s
  keepaliveTime: 0s
  myASN: 64512
  passwordSecret:
    name: secretname
    namespace: metallb-system
  peerASN: 64512
  peerAddress: 172.30.0.3
  peerPort: 180
