apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv-sample1
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-addresspool-sample1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv-sample2
  namespace: metallb-system  
spec:
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: kind-control-plane
