apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-sample1
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/24
  - 192.168.9.1-192.168.9.5
  - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-sample2
  namespace: metallb-system
  labels:
    test: ipv4
spec:
  addresses:
    - 172.20.0.100/24
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-sample3
  namespace: metallb-system
  labels:
    test: ipv6
spec:
  addresses:
    - 2002:2:2::1-2002:2:2::100
