apiVersion: metallb.io/v1alpha1
kind: BGPCommunity
metadata:
  name: bgpcommunity-sample1
spec:
  accept-oam: 7003:007

---
apiVersion: metallb.io/v1alpha1
kind: BGPCommunity
metadata:
  name: bgpcommunity-sample2
spec:
  accept-sig: 7002:007
