apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{.NameSpace}}'
  name: '{{.ConfigMapName}}'
data:
  config: |
    bgp-communities:
    {{ range $key, $value := .BGPCommunity }}
      {{ $key }}: {{ $value }}
    {{ end }}
