apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
- privileged-role-binding.yaml
transformers:
- custom-namespace-transformer.yaml
patches:
- path: patch-namespace.yaml
- path: patch-deployment-controller-manager.yaml
namespace: metallb-system
