# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/metallb.io_metallbs.yaml
  - bases/metallb.io_addresspools.yaml
  - bases/metallb.io_bgppeers.yaml
  - bases/metallb.io_bfdprofiles.yaml
  - bases/metallb.io_ippools.yaml
  - bases/metallb.io_l2advertisements.yaml
  - bases/metallb.io_bgpadvertisements.yaml

# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
