apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: webhook-server
        args:
        - --disable-cert-rotation=true
        - --port=7472
        - --log-level=info
        - --webhook-mode=onlywebhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --enable-leader-election
        - --disable-cert-rotation=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frr-k8s-webhook-server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: frr-k8s-webhook-server
        args:
        - --disable-cert-rotation=true
        - --log-level=info
        - --webhook-mode=onlywebhook
        - --namespace=$(NAMESPACE)
        - --health-probe-bind-address=:8081
