apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{.NameSpace}}'
  name: config
data:
  config: |
    address-pools:
    - name: {{ .Name }}
      protocol: {{ .Protocol }}
      addresses:

      {{ range $address := .Addresses -}}
      - {{ $address }}
      {{ end -}}

      {{ $auto_assign := .AutoAssign }} {{ if not $auto_assign }}
      auto-assign: {{ $auto_assign }}
      {{ end }}

      {{ $advlen := len .BgpAdvertisements }} {{ if gt $advlen 0 }}
      bgp-advertisements:
      {{ range $adv := .BgpAdvertisements -}}
        {{ if ne $adv.AggregationLength 0 }}
          - aggregation-length: {{ $adv.AggregationLength }}
        {{ end }}
        {{ if ne $adv.LocalPref 0 }}
          localpref: {{ $adv.LocalPref }}
        {{ end }}
        {{ $commlen := len $adv.Communities }} {{ if gt $commlen 0 }}
          communities:
          {{ range $comm := $adv.Communities -}}
            - {{ $comm }}
          {{ end -}}
        {{ end }}
      {{ end -}}
      {{ end -}}

